//! Functions for implementing a media repo.

/// Checks whether a given `Content-Type` is considered "safe" for having a `Content-Disposition` of
/// `inline`. This should be used on `/download` only, as `/thumbnail` should only ever return safe
/// types as thumbnails are generated by the server.
pub fn is_safe_content_type(content_type: &str) -> bool {
    const SAFE_CONTENT_TYPES: [&str; 26] = [
        "text/css",
        "text/plain",
        "text/csv",
        "application/json",
        "application/ld+json",
        "image/jpeg",
        "image/gif",
        "image/png",
        "image/apng",
        "image/webp",
        "image/avif",
        "video/mp4",
        "video/webm",
        "video/ogg",
        "video/quicktime",
        "audio/mp4",
        "audio/webm",
        "audio/aac",
        "audio/mpeg",
        "audio/ogg",
        "audio/wave",
        "audio/wav",
        "audio/x-wav",
        "audio/x-pn-wav",
        "audio/flac",
        "audio/x-flac",
    ];

    SAFE_CONTENT_TYPES.contains(&content_type)
}
