//! Implementations and types to parse the `ruma_id` macro input.

use proc_macro2::Span;
use quote::quote;
use syn::{meta::ParseNestedMeta, parse_quote};

use super::{RumaId, StorageCfgAttributes, Types};
use crate::util::RumaCommon;

/// The default size of the inline array for the `SmallVec` inner representation.
const SMALLVEC_INLINE_BYTES_DEFAULT: usize = 32;

impl RumaId {
    /// Parse the given `ruma_id` macro input.
    pub(super) fn parse(ruma_id_attrs: RumaIdAttrs, item: syn::ItemStruct) -> syn::Result<Self> {
        if !item.fields.is_empty() {
            return Err(syn::Error::new(
                Span::call_site(),
                "Only structs without fields are supported, \
                 the inner representation is generated by the ruma_id macro",
            ));
        }

        let RumaIdAttrs { validate, smallvec_inline_bytes } = ruma_id_attrs;

        if validate.is_none() && !item.generics.params.is_empty() {
            return Err(syn::Error::new(
                Span::call_site(),
                "IDs without validation and with generics are not supported",
            ));
        }

        if item.generics.where_clause.is_some() {
            // So we don't have to insert #where_clause everywhere when it is always None in
            // practice.
            return Err(syn::Error::new(
                Span::call_site(),
                "where clauses on IDs are not supported",
            ));
        }

        if let Some(param) =
            item.generics.params.iter().find(|param| !matches!(param, syn::GenericParam::Type(_)))
        {
            return Err(syn::Error::new_spanned(
                param,
                "Only generic type parameters are supported",
            ));
        }

        let generics = item.generics;
        let (impl_generics, type_generics, _where_clause) = generics.split_for_impl();
        let impl_generics = quote! { #impl_generics };

        let ident = item.ident;
        let id_type = parse_quote! { #ident #type_generics };

        let smallvec_inline_bytes = smallvec_inline_bytes.unwrap_or(SMALLVEC_INLINE_BYTES_DEFAULT);

        let ruma_common = RumaCommon::new();
        let types = Types::new(&ruma_common, smallvec_inline_bytes);

        Ok(Self {
            ident,
            attrs: item.attrs,
            vis: item.vis,
            id_type,
            generics,
            impl_generics,
            validate,
            smallvec_inline_bytes,
            storage_attrs: StorageCfgAttributes::new(),
            types,
            ruma_common,
        })
    }
}

/// The parsed attributes of the `ruma_id` attribute of the `ruma_id` attribute macro.
#[derive(Default)]
pub(crate) struct RumaIdAttrs {
    /// The path to the function to use to validate the identifier.
    validate: Option<syn::Path>,

    /// The size of the inline array for the `SmallVec` inner representation.
    smallvec_inline_bytes: Option<usize>,
}

impl RumaIdAttrs {
    /// Set the path to the function to use to validate the identifier.
    ///
    /// Returns an error if it is already set.
    fn set_validate(&mut self, validate: syn::Path, meta: &ParseNestedMeta<'_>) -> syn::Result<()> {
        if self.validate.is_some() {
            return Err(meta.error("cannot have multiple values for `validate` attribute"));
        }

        self.validate = Some(validate);
        Ok(())
    }

    /// Set the size of the inline array for the `SmallVec` inner representation.
    ///
    /// Returns an error if it is already set or if the value doesn't fit into a `usize`.
    fn set_smallvec_inline_bytes(
        &mut self,
        inline_bytes: syn::LitInt,
        meta: &ParseNestedMeta<'_>,
    ) -> syn::Result<()> {
        if self.smallvec_inline_bytes.is_some() {
            return Err(
                meta.error("cannot have multiple values for `smallvec_inline_bytes` attribute")
            );
        }

        self.smallvec_inline_bytes = Some(inline_bytes.base10_parse()?);
        Ok(())
    }

    /// Try to parse the given meta item and merge it into this `RumaIdAttrs`.
    ///
    /// Returns an error if an unknown `ruma_id` attribute is encountered, or if an attribute
    /// that accepts a single value appears several times.
    pub(crate) fn try_merge(&mut self, meta: ParseNestedMeta<'_>) -> syn::Result<()> {
        if meta.path.is_ident("validate") {
            return self.set_validate(meta.value()?.parse()?, &meta);
        }

        if meta.path.is_ident("smallvec_inline_bytes") {
            return self.set_smallvec_inline_bytes(meta.value()?.parse()?, &meta);
        }

        Err(meta.error("unsupported `ruma_id` attribute"))
    }
}
