//! Implementations and types to parse the `ruma_id` macro input.

use proc_macro2::Span;
use quote::quote;
use syn::parse_quote;

use super::RumaId;
use crate::{
    identifiers::{RumaIdAttrs, SMALLVEC_INLINE_BYTES_DEFAULT, StorageCfgAttributes, Types},
    util::RumaCommon,
};

impl RumaId {
    /// Parse the given `ruma_id` macro input.
    pub(super) fn parse(ruma_id_attrs: RumaIdAttrs, item: syn::ItemStruct) -> syn::Result<Self> {
        if !item.fields.is_empty() {
            return Err(syn::Error::new(
                Span::call_site(),
                "Only structs without fields are supported, \
                 the inner representation is generated by the ruma_id macro",
            ));
        }

        let RumaIdAttrs { validate, smallvec_inline_bytes } = ruma_id_attrs;

        if validate.is_none() && !item.generics.params.is_empty() {
            return Err(syn::Error::new(
                Span::call_site(),
                "IDs without validation and with generics are not supported",
            ));
        }

        if item.generics.where_clause.is_some() {
            // So we don't have to insert #where_clause everywhere when it is always None in
            // practice.
            return Err(syn::Error::new(
                Span::call_site(),
                "where clauses on IDs are not supported",
            ));
        }

        if let Some(param) =
            item.generics.params.iter().find(|param| !matches!(param, syn::GenericParam::Type(_)))
        {
            return Err(syn::Error::new_spanned(
                param,
                "Only generic type parameters are supported",
            ));
        }

        let generics = item.generics;
        let (impl_generics, type_generics, _where_clause) = generics.split_for_impl();
        let impl_generics = quote! { #impl_generics };

        let ident = item.ident;
        let id_type = parse_quote! { #ident #type_generics };

        let smallvec_inline_bytes = smallvec_inline_bytes.unwrap_or(SMALLVEC_INLINE_BYTES_DEFAULT);

        let ruma_common = RumaCommon::new();
        let types = Types::new(&ruma_common, smallvec_inline_bytes);

        Ok(Self {
            ident,
            attrs: item.attrs,
            vis: item.vis,
            id_type,
            generics,
            impl_generics,
            validate,
            smallvec_inline_bytes,
            storage_attrs: StorageCfgAttributes::new(),
            types,
            ruma_common,
        })
    }
}
