#[cfg(feature = "unstable-msc4354")]
use std::time::Duration;

use js_int::Int;
use ruma_common::{
    OwnedEventId, OwnedTransactionId, room_version_rules::RedactionRules, serde::CanBeEmpty,
};
use serde::{Deserialize, Serialize};
use serde_json::value::RawValue as RawJsonValue;

use super::{
    BundledStateRelations, EphemeralRoomEventContent, EphemeralRoomEventType, EventContentFromType,
    GlobalAccountDataEventContent, GlobalAccountDataEventType, MessageLikeEventContent,
    MessageLikeEventType, PossiblyRedactedStateEventContent, RedactContent,
    RedactedMessageLikeEventContent, RedactedStateEventContent, RoomAccountDataEventContent,
    RoomAccountDataEventType, StateEventContent, StateEventType, StateUnsigned,
    StaticStateEventContent, ToDeviceEventContent, ToDeviceEventType,
};

macro_rules! custom_event_content {
    ($i:ident, $evt:ident) => {
        /// A custom event's type. Used for event enum `_Custom` variants.
        // FIXME: Serialize shouldn't be required here, but it's currently a supertrait of
        // EventContent
        #[derive(Clone, Debug, Serialize)]
        #[allow(clippy::exhaustive_structs)]
        pub struct $i {
            #[serde(skip)]
            event_type: Box<str>,
        }

        impl EventContentFromType for $i {
            fn from_parts(event_type: &str, _content: &RawJsonValue) -> serde_json::Result<Self> {
                Ok(Self { event_type: event_type.into() })
            }
        }
    };
}

macro_rules! custom_room_event_content {
    ($i:ident, $evt:ident) => {
        custom_event_content!($i, $evt);

        impl RedactContent for $i {
            type Redacted = Self;

            fn redact(self, _: &RedactionRules) -> Self {
                self
            }
        }
    };
}

custom_event_content!(CustomGlobalAccountDataEventContent, GlobalAccountDataEventType);
impl GlobalAccountDataEventContent for CustomGlobalAccountDataEventContent {
    fn event_type(&self) -> GlobalAccountDataEventType {
        self.event_type[..].into()
    }
}

custom_event_content!(CustomRoomAccountDataEventContent, RoomAccountDataEventType);
impl RoomAccountDataEventContent for CustomRoomAccountDataEventContent {
    fn event_type(&self) -> RoomAccountDataEventType {
        self.event_type[..].into()
    }
}

custom_event_content!(CustomEphemeralRoomEventContent, EphemeralRoomEventType);
impl EphemeralRoomEventContent for CustomEphemeralRoomEventContent {
    fn event_type(&self) -> EphemeralRoomEventType {
        self.event_type[..].into()
    }
}

custom_room_event_content!(CustomMessageLikeEventContent, MessageLikeEventType);
impl MessageLikeEventContent for CustomMessageLikeEventContent {
    fn event_type(&self) -> MessageLikeEventType {
        self.event_type[..].into()
    }
}
impl RedactedMessageLikeEventContent for CustomMessageLikeEventContent {
    fn event_type(&self) -> MessageLikeEventType {
        self.event_type[..].into()
    }
}

custom_room_event_content!(CustomStateEventContent, StateEventType);
impl StateEventContent for CustomStateEventContent {
    type StateKey = String;

    fn event_type(&self) -> StateEventType {
        self.event_type[..].into()
    }
}
impl StaticStateEventContent for CustomStateEventContent {
    type Unsigned = CustomStateUnsigned;
    type PossiblyRedacted = Self;
}
impl PossiblyRedactedStateEventContent for CustomStateEventContent {
    type StateKey = String;

    fn event_type(&self) -> StateEventType {
        self.event_type[..].into()
    }
}
impl RedactedStateEventContent for CustomStateEventContent {
    type StateKey = String;

    fn event_type(&self) -> StateEventType {
        self.event_type[..].into()
    }
}

/// Extra information about a custom state event that is not incorporated into the event's hash.
///
/// This is the same as [`StateUnsigned`] but without the `prev_content` field, because it would
/// only contain the event type which is the same as the parent event.
#[derive(Clone, Debug, Default, Deserialize)]
#[cfg_attr(not(ruma_unstable_exhaustive_types), non_exhaustive)]
pub struct CustomStateUnsigned {
    /// The time in milliseconds that has elapsed since the event was sent.
    ///
    /// This field is generated by the local homeserver, and may be incorrect if the local time on
    /// at least one of the two servers is out of sync, which can cause the age to either be
    /// negative or greater than it actually is.
    pub age: Option<Int>,

    /// The client-supplied transaction ID, if the client being given the event is the same one
    /// which sent it.
    pub transaction_id: Option<OwnedTransactionId>,

    /// The event ID of the state event replaced by this event.
    pub replaces_state: Option<OwnedEventId>,

    /// [Bundled aggregations] of related child events.
    ///
    /// [Bundled aggregations]: https://spec.matrix.org/v1.19/client-server-api/#aggregations-of-child-events
    #[serde(rename = "m.relations", default)]
    pub relations: BundledStateRelations,

    /// Milliseconds remaining until this sticky event expires.
    ///
    /// Only present in `/sync` responses for sticky events. See [MSC4354].
    ///
    /// [MSC4354]: https://github.com/matrix-org/matrix-spec-proposals/pull/4354
    #[cfg(feature = "unstable-msc4354")]
    #[serde(rename = "msc4354_sticky_duration_ttl_ms", default)]
    #[serde(with = "ruma_common::serde::duration::opt_ms")]
    pub sticky_duration_ttl_ms: Option<Duration>,
}
impl CanBeEmpty for CustomStateUnsigned {
    /// Whether this unsigned data is empty (all fields are `None`).
    ///
    /// This method is used to determine whether to skip serializing the `unsigned` field in room
    /// events. Do not use it to determine whether an incoming `unsigned` field was present - it
    /// could still have been present but contained none of the known fields.
    fn is_empty(&self) -> bool {
        let Self {
            age,
            transaction_id,
            replaces_state,
            relations,
            #[cfg(feature = "unstable-msc4354")]
            sticky_duration_ttl_ms,
        } = self;
        let empty = age.is_none()
            && transaction_id.is_none()
            && replaces_state.is_none()
            && relations.is_empty();
        #[cfg(feature = "unstable-msc4354")]
        let empty = empty && sticky_duration_ttl_ms.is_none();
        empty
    }
}
// This is only used as an exhaustive check to make sure that the types keep all the same fields
// except `prev_content`.
#[doc(hidden)]
impl<C: PossiblyRedactedStateEventContent> From<StateUnsigned<C>> for CustomStateUnsigned {
    fn from(value: StateUnsigned<C>) -> Self {
        let StateUnsigned {
            age,
            transaction_id,
            replaces_state,
            prev_content: _,
            relations,
            #[cfg(feature = "unstable-msc4354")]
            sticky_duration_ttl_ms,
        } = value;
        Self {
            age,
            transaction_id,
            replaces_state,
            relations,
            #[cfg(feature = "unstable-msc4354")]
            sticky_duration_ttl_ms,
        }
    }
}

custom_event_content!(CustomToDeviceEventContent, ToDeviceEventType);
impl ToDeviceEventContent for CustomToDeviceEventContent {
    fn event_type(&self) -> ToDeviceEventType {
        self.event_type[..].into()
    }
}
