[package]
name = "ruma-serde"
description = "De-/serialization helpers for other ruma crates"
license = "MIT"
homepage = "https://www.ruma.io/"
repository = "https://github.com/ruma/ruma"
version = "0.6.0"
edition = "2018"

[dependencies]
base64 = "0.13.0"
bytes = "1.0.1"
form_urlencoded = "1.0.0"
itoa = "1.0.1"
js_int = { version = "0.2.0", features = ["serde"] }
ruma-macros = { version = "=0.1.0", path = "../ruma-macros" }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = { version = "1.0.61", features = ["raw_value"] }

[dev-dependencies]
matches = "0.1.8"
ruma-common = { path = "../ruma-common" , version = "0.8.0"}
