name: Style

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main, next]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Check spelling
        uses: crate-ci/typos@master
      - name: Install cargo-sort
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-sort
      - name: Run lints
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p xtask --no-default-features ci lint
